### PR TITLE
hireable.me now has SSL Certificate

### PR DESCRIPTION
**Pull request by nguyenph88**
Please don't merge yet, i'm still configuring this on my end.

### CODE REVIEW

**Comment by nguyenph88** [comment]
@hiendv i need your help to generate the CSR code on your server.
https://www.namecheap.com/support/knowledgebase/article.aspx/467/67/how-do-i-generate-a-csr-code

Please send it to my email. Thanks.

**Comment by hiendv** [comment]
Email sent! Further technical discussions will continue using email.

**Comment by hiendv** [comment]
Closed because I made a ton of changes to the codebase. Sorry for the inconvenience. Could you please sync the remote and fire another PR. Thank you.

**Comment by nguyenph88** [comment]
awesome jobs Hien! :) thanks for your help

**Comment by hiendv** [comment]
@nguyenph88 You're helping me so much actually :+1:

**Pull request closed without merging**
